version: "3.9"

services:
  web:
    image: nginx:alpine
    container_name: infraweave-crm
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "3002:80"
    restart: always
