services:
  orgware:
    image: oarkflow/web-server:latest
    platform: linux/amd64
    container_name: orgware
    volumes:
      - ./orgware.env:/.env:ro # mount your .env into /app/.env (read‑only)
      - ./orgware:/static/public # mount local assets dir into /app/assets
    ports:
      - "3004:3004" # map host 3004 to container 3004
    restart: unless-stopped
  demo1:
    image: oarkflow/web-server:latest
    platform: linux/amd64
    container_name: demo1
    volumes:
      - ./demo1.env:/.env:ro # mount your .env into /app/.env (read‑only)
      - ./demo1:/static/public # mount local assets dir into /app/assets
    ports:
      - "3003:3003" # map host 8081 to container 8080
    restart: unless-stopped

  demo2:
    image: oarkflow/web-server:latest
    platform: linux/amd64
    container_name: demo2
    volumes:
      - ./demo2.env:/.env:ro
      - ./demo2:/static/public
    ports:
      - "3002:3002" # map host 8082 to container 8080
    restart: unless-stopped

  sujit-baniya:
    image: oarkflow/web-server:latest
    platform: linux/amd64
    container_name: sujit-baniya
    volumes:
      - ./sujit-baniya.env:/.env:ro
      - ./sujit-baniya:/static/public
    ports:
      - "3001:3001" # map host 8082 to container 8080
    restart: unless-stopped

  verishore:
    image: oarkflow/web-server:latest
    platform: linux/amd64
    container_name: verishore
    volumes:
      - ./verishore.env:/.env:ro
      - ./verishore:/static/public
    ports:
      - "3000:3000" # map host 8082 to container 8080
    restart: unless-stopped
