version: "3.9"

services:
  web:
    image: nginx:alpine
    container_name: dist_server
    volumes:
      - ./infraweave:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "3001:80"
    restart: always
