services:
  infraweave:
    image: oarkflow/web-server:latest
    platform: linux/amd64
    container_name: orgware
    volumes:
      - ./infraweave.env:/.env:ro # mount your .env into /app/.env (readâ€‘only)
      - ./infraweave:/static/public # mount local assets dir into /app/assets
    ports:
      - "3001:3001" # map host 3004 to container 3004
