version: "3.9"

services:
  web:
    image: nginx:alpine
    container_name: dist_server
    volumes:
      - ./dist:/usr/share/nginx/html:ro   # Serve your dist folder
    ports:
      - "3001:80"                         # Expose dist at http://localhost:3001
    restart: always
